// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Message struct {
	MessageID   string `json:"message_id"`
	Sender      *User  `json:"sender"`
	Receiver    *User  `json:"receiver"`
	MessageBody string `json:"message_body"`
	SentAt      string `json:"sent_at"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	UserID           string     `json:"user_id"`
	Username         string     `json:"username"`
	Email            string     `json:"email"`
	CreatedAt        string     `json:"created_at"`
	SentMessages     []*Message `json:"sentMessages"`
	ReceivedMessages []*Message `json:"receivedMessages"`
}
